### PR TITLE
FIX dead link to etcd2 config documentation

### PR DESCRIPTION
**Pull request by petrus-v**

### CODE REVIEW

**Comment by crawford** [comment]
Can you link to the v2.3.2 tag instead of master (so this doesn't break in the future)? Can you also update your commit message to match the contribution guide?

**Comment by petrus-v** [comment]
@crawford,

Yes sure I'll!

**Comment by petrus-v** [comment]
@crawford,

I've updated the PR according your requirement, as I'm newbie here I'm wondering 3 things:
* Why the *etcd* v2.3.2 and not v2.3.5?
* This link is going to get obsolete over the time, isn't it? (but I've no obvious solution today fix that problem)
* Does it make sense to create a PR against [documentation style](https://github.com/coreos/docs/blob/master/STYLE.md#hyperlink-considerations) about external links hosted on [coreos.com](https://coreos.com) it's not obvious to link to github markdown file over than the html website?

**Comment by crawford** [comment]
> Why the etcd v2.3.2 and not v2.3.5?

Because coreos-cloudinit supports v2.3.2. Theoretically the options haven't changed, but I'd rather go with the version that was explicitly supported.

> This link is going to get obsolete over the time, isn't it?

Yep, we'll have to keep it up to date. Better than a 404 though.

> it's not obvious to link to github markdown file over than the html website

These repos shouldn't generally link to coreos.com. The source should be able to stand on its own.

**Comment by petrus-v** [comment]
@crawford 

Thanks for reply!

**Pull request merged**
