### PR TITLE
use omitempty for yaml.Marshal

### PR DESCRIPTION
**Pull request by mikecook**

### CODE REVIEW

**Comment by crawford** [comment]
This project has been deprecated for quite a while now. What is the reason for this proposed change? Unless it fixes a serious bug, my inclination is to reject this patch since we aren't likely to cut and ship any more releases.

**Comment by mikecook** [comment]
While deprecated, cloud-init is still valid for coreos.
I've got quite a bit of infrastructure still using cloud-init. Ignition doesn't make that existing infrastructure go away. `omitempty` solves some problems managing that infrastructure.
If ignition supported cloud-config I'd use that in a heartbeat.
I've still got to fix the tests, why they break when a yaml tag flag is used will be fun to figure out.

**Comment by crawford** [comment]
> `omitempty` solves some problems managing that infrastructure.

I'm interested to hear about these problems.

**Comment by mikecook** [comment]
Using a deploy tool to add organizational level units/files/settings to existing cloud-configs.

**Comment by mikecook** [comment]
Actually, these tests are too fragile for me to spend so much time fixing them when the code works. If there was a higher likelihood of PR acceptance, then maybe. As is, I'll find a different solution.

**Pull request closed without merging**
