### PR TITLE
Filled cloud providers cloud-config URLs

### PR DESCRIPTION
**Pull request by kayrus**
/cc @robszumski

### CODE REVIEW

**Comment by crawford** [comment]
LGTM

**Comment by robszumski** [comment]
Should we make this whole thing a table? It's pretty hard to read.

**Comment by kayrus** [comment]
Fixed.

**Comment by robszumski** [comment]
LGTM

**Comment by kayrus** [comment]
merge?

**Comment by marineam** [comment]
Your wish is my command

**Pull request merged**
