### PR TITLE
coreos compatibility with opennebula

### PR DESCRIPTION
**Pull request by SlavomirPolak**
Hi,

we are working on compatibility of coreos with opennebula. We added opennebula_drive package(configdrive for opennebula) to coreos-cloudinit/datasource/opennebula_drive/ and new units scripts to coreos-cloudinit/units/. We would like to know, what needs to be done when we added new units scripts.

Slavomir Polak

### CODE REVIEW

**Comment by crawford** [comment]
I don't think anything else will need to be done. The [coreos-cloudinit ebuild](https://github.com/coreos/coreos-overlay/blob/master/coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild) will pull in all of the additional files.

Can you squash the commits and fix up the commit message according to the [contribution documentation](https://github.com/coreos/coreos-cloudinit/blob/master/CONTRIBUTING.md)?

**Comment by SlavomirPolak** [comment]
I fixed up commit messages and squashed them.

**Comment by crawford** [comment]
It looks like there was trouble building this.

**Comment by crawford** [comment]
Closing due to inactivity.

**Pull request closed without merging**
