### PR TITLE
config: deprecate fetching SSH keys from remote endpoints

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by mischief** [comment]
lgtm

the convenience was nice but the network/user setup ordering problems are not.

**Comment by Nosmoht** [comment]
Hi All,

just yesterday i implemented this nice feature in our environment. If this parameter is not deprecated what is the recommended way of getting SSH keys from a local/internal Github Enterprise system?

**Comment by crawford** [comment]
@Nosmoht the SSH keys for the machine should be injected directly into the cloud-config or managed by a proper configuration management tool.

**Comment by Nosmoht** [comment]
@crawford Thanks for your answer. We are deploying CoreOS nodes using Ansible and Foreman. So the users/keys are already provided by a configuration management tool. The problem with the approach of putting public keys into cloud-config is that i need to have every single key. So i always have to talk to people and can't automate the infrastructure provisioning.

That's why, from my point of view, this "depcreated" feature is such nice. With it, i have only one single point of data (Github) instead of storing public key files in multiple repositories, keeping them in sync and so on.

**Pull request merged**
