### PR TITLE
cleanup deps, update to libcontainer v2.1.1

### PR DESCRIPTION
**Pull request by imikushin**
Removed stale dependencies. Updated libcontainer to latest production version: 
libcontainer v2.1.1 is used by docker v1.7.0

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Hey CoreOS folks.  Just a bit of context here.  In RancherOS we use the datasources from coreos-cloudinit and some other code.  We'd love to be able to collaborate on this project and hopefully commit back any changes when might do.  The problem at the moment is with the import paths currently used.  It seems to really confuse godeps such that we can use godeps in RancherOS and include coreos-cloudinit.  Because of this we had to fork the project just to update the import paths (and use a newer libcontainer for netlink).

Would you guys be up to switching to a more traditional godeps approach?

**Comment by crawford** [comment]
@ibuildthecloud dependency management in go is so miserable. We need to keep the modified import paths, otherwise go won't be able to find our vendored version of the dependencies. What do you mean by a "traditional godeps approach"?

**Comment by imikushin** [comment]
@crawford I think, @ibuildthecloud meant using `godep` tool in the build. "traditional" might be too strong a word, but it does allow to keep both unchanged package names and sanity (to some extent).

[godep](https://github.com/tools/godep) is a tool that allows to use and manage the vendored version of dependencies. Prepend your `go` command with `godep` and it will use the vendored dependencies (instead of those in your local GOPATH). E.g. 
```bash
godep go build -o bin/coreos-cloudinit
``` 
does the same as `go build -o bin/coreos-cloudinit`, but using the libs from ./Godeps/_workspace/src

**Comment by crawford** [comment]
Ah, that makes sense. Let me dig into this a little bit.

**Comment by crawford** [comment]
Unfortunately, it looks as though we won't be able to accept this change. Our build system does not have any notion of godep and we will not be adding it. It looks as though golang 1.5 should solve this issue with its vendor support. I've opened [this issue](https://github.com/coreos/coreos-cloudinit/issues/361) to track the migration to that new scheme.

**Comment by imikushin** [comment]
@crawford this particular PR doesn't use godep, just adds ./Godeps/_workspace to GOPATH and uses updated version of libcontainer (the one used in docker 1.7)

**Comment by ibuildthecloud** [comment]
@crawford I believe this will work in your build system.  If not I guess we will try again later, which is a shame.

**Comment by crawford** [comment]
We don't use the build scripts in our build system. The changes to the GOPATH you've made there won't have any effect in our build system. We will revisit this in a few weeks once we have golang 1.5. I hate this as much as you do.

**Comment by marineam** [comment]
Just to be clear, the "build system" @crawford is referring to is the cloudinit ebuild which uses our Go eclass: https://github.com/coreos/coreos-overlay/blob/master/eclass/coreos-go.eclass

The eclass is capable of handling cross-compiles and CGO properly for CoreOS while the simple `build` script does not and is just there as a developer aid.

**Pull request closed without merging**
