### PR TITLE
unit: fix oem-cloudinit reference

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by mischief** [comment]
is there an open bug for this?

**Comment by crawford** [comment]
No. It was mentioned here: https://groups.google.com/forum/#!searchin/coreos-user/ec2-cloudinit/coreos-user/LkxQ-FhxTjI/G6zaHQhJBQAJ.

**Comment by crawford** [comment]
Long ago, all of these services were renamed to oem-cloudinit (from ec2-cloudinit, gce-cloudinit, etc.).

**Comment by mischief** [comment]
noted. lgtm

**Comment by mischief** [comment]
will this need to be backported?

**Comment by crawford** [comment]
Probably not. This has been broken for a long time. At this point, I wonder if it is safer to just remove it altogether.

**Pull request merged**
